version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: .
    command: diesel migration run
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres

  authentication:
    build: .
    depends_on:
      - migrate
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml:/app/config.toml
      - ./private_key.pem:/app/private_key.pem
      - ./public_key.pem:/app/public_key.pem

volumes:
  postgres_data:
